spring.application.name=ShoppingApp
server.port=8080

spring.datasource.username=sujal
spring.datasource.password=tambe

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true

spring.jpa.show-sql=true
